# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness

url: http://furkanbayram.online
baseurl: '/' 
title: Şefik Furkan Bayram - Yazılım ve Tasarım
gems:
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
author: Şefik Furkan Bayram
job: Frontend Developer
description: Kişisel Blog ve Yazılım
avatar: profileImage.jpg
facebook: profile.php?id=100006148155735
email: sefikfurkanbayram@gmail.com
github: furkanbayram2 # username
twitter: username
instagram: furkanbayram2
linkedin: sefikfurkanbayram
disqus: disqus_4bZIHJEcMy
google_analytics: UA-96537358-2
exclude: [vendor]
